# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""``ledger_issue_contains`` and ``pull_request_opened`` on a GitLab project.

Over the recorded, anonymised gitlab.com payloads in ``fixtures/gitlab/``
(see ``test_gitlab_writes.py`` for where they came from): ``issue-open.json``
and ``issue-closed.json`` are one issue as GitLab returned it on create and
on close, ``issue-notes.json`` its notes, ``mr-view.json`` an open merge
request, ``mr-closed.json`` a closed one with its ``mr-commits.json``. A test
that needs a ledger body or a stamp writes it onto the recorded shape; the
shape, the field names and the URL forms are GitLab's own.
"""

from __future__ import annotations

import copy
import json
from datetime import datetime, timezone
from pathlib import Path

import pytest
from kube_agents_bench import forges, github_writes, transcript, verifiers
from kube_agents_bench.verifiers import LedgerIssueContainsVerifier, PullRequestOpenedVerifier

FIXTURES = Path(__file__).parent / "fixtures" / "gitlab"
REPO = "example-group/infra"
PROJECT = "https://gitlab.com/api/v4/projects/example-group%2Finfra"
AUDIT = "compliance-audit"
# The run starts at 14:59:30Z; the ledger is stamped 20s later, !3 opened at
# 14:59:51Z and its head committed at 14:59:48Z.
RUN_START = datetime(2026, 10, 1, 14, 59, 30, tzinfo=timezone.utc)
STAMP = "2026-10-01T14:59:50+00:00"
ISSUE_URL = f"https://gitlab.com/{REPO}/-/work_items/1"
MR3_URL = f"https://gitlab.com/{REPO}/-/merge_requests/3"


def fixture(name: str):
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def ledger_body(stamp: str = STAMP, findings: str = "rbac-overgrant on seeded-a") -> str:
    return (
        f"# Audit ledger\n\n### {findings}\n\n---\n\n"
        f"Generated by the Platform Agent `{AUDIT}` watchdog at {stamp}. "
        "Findings come from read-only inspection of the live fleet.\n\n"
        '<!-- audit-findings: ["rbac-overgrant.seeded-a._.debug-binding"] -->\n'
        "<!-- audit-id-scheme: 2 -->\n"
    )


def ledger(stamp: str = STAMP, closed: bool = False) -> dict:
    issue = fixture("issue-closed.json" if closed else "issue-open.json")
    issue["description"] = ledger_body(stamp)
    issue["labels"] = ["agent:audit", f"audit:{AUDIT}"]
    return issue


@pytest.fixture
def env(monkeypatch):
    monkeypatch.setenv(forges.FORGE_ENV_VAR, "gitlab")
    monkeypatch.setenv("BENCH_GITLAB_TOKEN", "glpat-fake")
    monkeypatch.delenv(forges.GITLAB_HOST_ENV_VAR, raising=False)
    monkeypatch.delenv("BENCH_GITHUB_TOKEN", raising=False)
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)


@pytest.fixture
def gitlab(monkeypatch):
    calls: list[str] = []
    routes: dict[str, object] = {}

    def fake_get(url: str, tok: str, timeout: float):
        calls.append(url)
        return routes.get(url, (404, {"message": "404 Not found"}))

    monkeypatch.setattr(verifiers, "_http_get_json", fake_get)
    return type("GL", (), {"routes": routes, "calls": calls})()


def stash(final_message: str):
    transcript.set("full output", [], final_message=final_message, started_at=RUN_START.timestamp())


def ledger_check(**kw) -> LedgerIssueContainsVerifier:
    return LedgerIssueContainsVerifier(type="ledger_issue_contains", audit=AUDIT, **kw)


def pr_check(**kw) -> PullRequestOpenedVerifier:
    kw.setdefault("owner", "example-group")
    return PullRequestOpenedVerifier(type="pull_request_opened", **kw)


# --- the URL forms ----------------------------------------------------------


def test_the_ledger_token_names_are_the_github_forge_names_as_a_literal():
    # The CI pool checker parses the literal tuple out of verifiers.py
    # (scripts/test_verify_ci_pool_project.py); the forge table must agree.
    assert verifiers.LEDGER_TOKEN_ENV_VARS == forges.GITHUB_TOKEN_ENV_VARS
    source = Path(verifiers.__file__).read_text()
    assert 'LEDGER_TOKEN_ENV_VARS = ("BENCH_GITHUB_TOKEN", "GITHUB_TOKEN")' in source


def test_both_gitlab_issue_url_forms_and_nested_paths_are_read():
    text = (
        f"ledger {ISSUE_URL}, also https://gitlab.com/a/b/c/-/issues/7 and "
        "https://github.com/a/b/issues/9 and https://gitlab.com/a/b/-/merge_requests/2"
    )
    assert forges.issue_refs(text, "gitlab") == [(REPO, 1), ("a/b/c", 7)]
    assert forges.issue_refs(text, "github") == [("a/b", 9)]
    assert forges.proposal_refs(text, "gitlab") == [("a/b", 2)]


def test_a_self_managed_host_is_the_only_one_read(monkeypatch):
    env = {forges.GITLAB_HOST_ENV_VAR: "git.example.com"}
    text = f"{ISSUE_URL} https://git.example.com/ops/infra/-/issues/4"
    assert forges.issue_refs(text, "gitlab", env) == [("ops/infra", 4)]


# --- ledger_issue_contains --------------------------------------------------


def test_a_gitlab_ledger_stamped_in_this_run_passes(env, gitlab):
    gitlab.routes[f"{PROJECT}/issues/1"] = (200, ledger())
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.success is True, result.reason
    assert result.raw["issue"] == f"{REPO}#1"
    assert gitlab.calls == [f"{PROJECT}/issues/1"]


def test_a_gitlab_ledger_from_a_previous_run_fails(env, gitlab):
    gitlab.routes[f"{PROJECT}/issues/1"] = (200, ledger(stamp="2026-09-30T10:00:00+00:00"))
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.success is False
    assert result.status != "error"
    assert "previous run's ledger" in result.reason


def test_a_gitlab_issue_without_the_stream_label_is_not_the_ledger(env, gitlab):
    issue = ledger()
    issue["labels"] = ["agent:audit", "audit:proto"]
    gitlab.routes[f"{PROJECT}/issues/1"] = (200, issue)
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check().verify(30)
    assert result.success is False
    assert "not labelled audit:compliance-audit" in result.reason


def test_a_closed_gitlab_ledger_is_a_false_clean_when_closed_in_the_run(env, gitlab):
    issue = ledger(stamp="2026-09-30T10:00:00+00:00", closed=True)
    issue["closed_at"] = "2026-10-01T14:59:40.000Z"
    gitlab.routes[f"{PROJECT}/issues/1"] = (200, issue)
    gitlab.routes[f"{PROJECT}/issues/1/notes?sort=desc&order_by=created_at&per_page=100"] = (
        200,
        fixture("issue-notes.json"),
    )
    stash(f"Closed as clean: {ISSUE_URL}")
    result = ledger_check().verify(30)
    assert result.success is False
    assert "a false clean" in result.reason
    assert result.raw["reset_by_harness"] is False


def test_the_reset_marker_is_read_from_gitlab_notes_skipping_system_notes(env, gitlab):
    issue = ledger(stamp="2026-09-30T10:00:00+00:00", closed=True)
    issue["closed_at"] = "2026-10-01T14:59:10.000Z"
    marker = fixture("issue-notes.json")[0]
    marker["body"] = f"{verifiers.LEDGER_RESET_MARKER}\nClosed before a repetition."
    marker["created_at"] = "2026-10-01T14:59:08.000Z"
    system = copy.deepcopy(marker)
    system["system"] = True
    notes_url = f"{PROJECT}/issues/1/notes?sort=desc&order_by=created_at&per_page=100"
    gitlab.routes[f"{PROJECT}/issues/1"] = (200, issue)
    stash(f"Ledger: {ISSUE_URL}")

    gitlab.routes[notes_url] = (200, [system])
    assert ledger_check().verify(30).raw["reset_by_harness"] is False

    gitlab.routes[notes_url] = (200, [system, marker])
    result = ledger_check().verify(30)
    assert result.raw["reset_by_harness"] is True
    assert "eval harness's ledger reset" in result.reason


def test_a_github_url_is_not_a_ledger_on_a_gitlab_run(env, gitlab):
    stash("Audit filed: https://github.com/example-group/infra/issues/1")
    result = ledger_check().verify(30)
    assert result.success is False
    assert "names no gitlab.com issue URL" in result.reason
    assert gitlab.calls == []


@pytest.mark.parametrize("status", [401, 403])
def test_a_gitlab_token_refused_is_an_error(env, gitlab, status):
    gitlab.routes[f"{PROJECT}/issues/1"] = (status, {"message": "401 Unauthorized"})
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check().verify(30)
    assert result.status == "error"
    assert f"GitLab returned {status}" in result.reason


def test_no_gitlab_token_is_an_error_naming_its_variable(env, gitlab, monkeypatch):
    monkeypatch.delenv("BENCH_GITLAB_TOKEN")
    stash(f"Audit filed: {ISSUE_URL}")
    for check in (ledger_check(), pr_check()):
        result = check.verify(30)
        assert result.status == "error"
        assert "BENCH_GITLAB_TOKEN" in result.reason


# --- pull_request_opened ----------------------------------------------------


def route_mr3(gitlab, **overrides) -> dict:
    mr = fixture("mr-view.json")
    mr["changes_count"] = "1"
    mr.update(overrides)
    gitlab.routes[f"{PROJECT}/merge_requests/3"] = (200, mr)
    gitlab.routes[f"{PROJECT}/repository/commits/{mr['sha']}"] = (200, fixture("commit-by-sha.json"))
    return mr


def test_a_merge_request_opened_in_the_run_passes(env, gitlab):
    route_mr3(gitlab)
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.success is True, result.reason
    assert result.raw == {
        "pull_request": f"{REPO}!3",
        "created_at": "2026-10-01T14:59:51.560000+00:00",
        "updated_at": "2026-10-01T14:59:52.865000+00:00",
        "changed_files": 1,
        "head_committed_at": "2026-10-01T14:59:48+00:00",
    }


def test_a_closed_merge_request_is_rejected_and_a_merged_one_is_not(env, gitlab):
    route_mr3(gitlab, state="closed")
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.success is False
    assert "closed without being merged" in result.reason
    route_mr3(gitlab, state="merged")
    assert pr_check().verify(30).success is True


def test_a_merge_request_changing_no_files_is_rejected(env, gitlab):
    route_mr3(gitlab, changes_count="0")
    stash(f"Opened {MR3_URL}")
    assert "changes no files" in pr_check().verify(30).reason


def test_a_capped_or_pending_change_count_is_not_zero(env, gitlab):
    route_mr3(gitlab, changes_count="1000+")
    stash(f"Opened {MR3_URL}")
    assert pr_check().verify(30).raw["changed_files"] == 1000
    route_mr3(gitlab, changes_count=None)
    result = pr_check().verify(30)
    assert result.success is True
    assert "an unreported number of" in result.reason


def test_a_leftover_merge_request_is_rejected(env, gitlab):
    route_mr3(gitlab, created_at="2026-09-30T10:00:00Z", updated_at="2026-09-30T10:00:00Z")
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.success is False
    assert "a leftover" in result.reason


def test_a_comment_on_an_old_head_is_not_a_push(env, gitlab):
    mr = route_mr3(gitlab, created_at="2026-09-30T10:00:00Z")
    old = fixture("commit-by-sha.json")
    old["committed_date"] = "2026-09-30T10:00:00.000+00:00"
    gitlab.routes[f"{PROJECT}/repository/commits/{mr['sha']}"] = (200, old)
    stash(f"Updated {MR3_URL}")
    result = pr_check().verify(30)
    assert result.success is False
    assert "head commit dates from" in result.reason


def test_a_merge_request_outside_the_owner_group_is_rejected(env, gitlab):
    stash("Opened https://gitlab.com/other-group/infra/-/merge_requests/3")
    result = pr_check().verify(30)
    assert result.success is False
    assert "not under example-group" in result.reason
    assert gitlab.calls == []


def test_a_missing_merge_request_is_absence_and_a_refused_token_an_error(env, gitlab, monkeypatch):
    # Configured, so the 404 on !3 asks whether the project itself is
    # visible -- and it is, so the 404 is the merge request's absence.
    # Review: unconfigured, the project read was never made and the test
    # passed the way the misnamed-project test does.
    configured(monkeypatch)
    gitlab.routes[PROJECT] = (200, {"id": 40000001})
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert PROJECT in gitlab.calls
    assert result.status != "error"
    assert "no such merge request" in result.reason
    gitlab.routes[f"{PROJECT}/merge_requests/3"] = (401, {"message": "401 Unauthorized"})
    result = pr_check().verify(30)
    assert result.status == "error"
    assert "GitLab answered 401" in result.reason


def test_no_merge_request_url_names_gitlab(env, gitlab):
    stash(f"Opened https://github.com/{REPO}/pull/3")
    result = pr_check().verify(30)
    assert result.success is False
    assert "no gitlab.com merge request URL" in result.reason


def route_spent(gitlab, *, carried: bool, named: bool, extra=()) -> str:
    """!3 on the branch closed !1 used, created inside the run."""
    route_mr3(gitlab, source_branch="platform-agent/proto-1")
    closed = fixture("mr-closed.json")
    closed["created_at"] = "2026-10-01T14:59:35.000Z"
    gitlab.routes[
        f"{PROJECT}/merge_requests?state=all&source_branch=platform-agent%2Fproto-1&per_page=100"
    ] = (200, [closed, *extra])
    commits = [{"id": fixture("commit-by-sha.json")["id"]}]
    if carried:
        commits += fixture("mr-commits.json")
    gitlab.routes[f"{PROJECT}/merge_requests/3/commits?per_page=100&page=1"] = (200, commits)
    return f"Opened {MR3_URL}" + (f" after closing https://gitlab.com/{REPO}/-/merge_requests/1" if named else "")


def test_a_second_merge_request_on_a_spent_branch_passes(env, gitlab):
    stash(route_spent(gitlab, carried=False, named=True))
    result = pr_check(reuses_spent_branch=True).verify(30)
    assert result.success is True, result.reason


def test_a_spent_branch_added_to_is_rejected(env, gitlab):
    stash(route_spent(gitlab, carried=True, named=True))
    result = pr_check(reuses_spent_branch=True).verify(30)
    assert result.success is False
    assert "the last revision of the closed merge request !1" in result.reason


def test_the_closed_merge_request_must_be_named(env, gitlab):
    stash(route_spent(gitlab, carried=False, named=False))
    result = pr_check(reuses_spent_branch=True).verify(30)
    assert result.success is False
    assert "does not name !1" in result.reason


# --- review round: a project the token cannot see, the stream window, forks --


def configured(monkeypatch, repo=REPO):
    monkeypatch.setenv(github_writes.GITOPS_REPO_ENV_VAR, repo)


def test_a_merge_request_404_on_a_project_the_token_cannot_see_is_an_error(env, gitlab, monkeypatch):
    # GitLab answers 404, not 403, for a private project the token is not a
    # member of: that is the credential's fault, not a number the agent got wrong.
    configured(monkeypatch)
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.status == "error"
    assert "cannot see it" in result.reason


def test_a_ledger_404_on_a_project_the_token_cannot_see_is_an_error(env, gitlab, monkeypatch):
    configured(monkeypatch)
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.status == "error"
    assert "cannot see it" in result.reason
    gitlab.routes[PROJECT] = (200, {"id": 40000001})
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.status != "error"
    assert "no such issue" in result.reason


def test_a_configured_path_copied_with_its_leading_slash_is_still_the_configured_project(env, gitlab, monkeypatch):
    # Review round 2: `github_writes` strips a leading slash from the GitLab
    # path and the project-read decision did not, so the same configuration
    # graded a project the token cannot see as the agent's failure.
    configured(monkeypatch, "/" + REPO)
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.status == "error", result.reason
    assert "cannot see it" in result.reason
    stash(f"Audit filed: {ISSUE_URL}")
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.status == "error", result.reason
    assert "cannot see it" in result.reason


def test_a_404_on_a_project_the_agent_named_wrongly_is_absence_not_an_error(env, gitlab, monkeypatch):
    # Review: only the configured project's 404 can be the credential's
    # fault. A path the agent mistyped is graded as no such object, as
    # GitHub grades a 404 pair, and its project is never read.
    configured(monkeypatch)
    typo = "example-group/infra-typo"
    stash(f"Opened https://gitlab.com/{typo}/-/merge_requests/3")
    result = pr_check().verify(30)
    assert result.status != "error", result.reason
    assert "no such merge request" in result.reason
    stash(f"Audit filed: https://gitlab.com/{typo}/-/issues/7")
    result = ledger_check(required_phrases=["rbac-overgrant"]).verify(30)
    assert result.status != "error", result.reason
    assert "no such issue" in result.reason
    typo_project = "https://gitlab.com/api/v4/projects/example-group%2Finfra-typo"
    assert typo_project not in gitlab.calls


def test_a_project_read_that_is_throttled_is_not_blamed_on_the_token(env, gitlab, monkeypatch):
    # Review: a 429 or a 5xx on the project read says nothing about the token.
    configured(monkeypatch)
    gitlab.routes[PROJECT] = (503, {"message": "unavailable"})
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.status == "error"
    assert "cannot see it" not in result.reason
    assert "503" in result.reason


def stream_env(monkeypatch, repo=REPO):
    monkeypatch.setenv(verifiers.STREAM_AUDIT_ENV_VAR, AUDIT)
    monkeypatch.setenv(verifiers.STREAM_REPO_ENV_VAR, repo)
    # The stream's first unit began a day before this run.
    monkeypatch.setenv(verifiers.STREAM_STARTED_ENV_VAR, str(RUN_START.timestamp() - 86400))


def test_accepts_stream_pull_request_widens_the_window_on_gitlab(env, gitlab, monkeypatch):
    stream_env(monkeypatch)
    route_mr3(gitlab, created_at="2026-09-30T20:00:00Z", updated_at="2026-09-30T20:00:00Z",
              source_branch=f"platform-agent/fix-{AUDIT}-1")
    old = fixture("commit-by-sha.json")
    old["committed_date"] = "2026-09-30T20:00:00.000+00:00"
    gitlab.routes[f"{PROJECT}/repository/commits/{fixture('mr-view.json')['sha']}"] = (200, old)
    stash(f"Opened {MR3_URL}")
    assert pr_check().verify(30).success is False
    result = pr_check(accepts_stream_pull_request=True).verify(30)
    assert result.success is True, result.reason
    # Review: said as GitHub says it -- not "during this run".
    assert "by an earlier run on this audit stream" in result.reason
    assert "during this run" not in result.reason


def test_a_stream_repository_spelled_with_a_slash_is_still_this_jobs(env, gitlab, monkeypatch):
    # Review: the configured-project decision normalised the stream
    # repository and the widened-window clause compared it raw, so a slash
    # copied out of a URL turned this job's own merge request into another's.
    stream_env(monkeypatch, repo=f"/{REPO}/")
    route_mr3(gitlab, created_at="2026-09-30T20:00:00Z", updated_at="2026-09-30T20:00:00Z",
              source_branch=f"platform-agent/fix-{AUDIT}-1")
    old = fixture("commit-by-sha.json")
    old["committed_date"] = "2026-09-30T20:00:00.000+00:00"
    gitlab.routes[f"{PROJECT}/repository/commits/{fixture('mr-view.json')['sha']}"] = (200, old)
    stash(f"Opened {MR3_URL}")
    result = pr_check(accepts_stream_pull_request=True).verify(30)
    assert result.success is True, result.reason


def test_the_widened_window_still_wants_the_streams_branch_and_repository(env, gitlab, monkeypatch):
    stream_env(monkeypatch)
    route_mr3(gitlab, created_at="2026-09-30T20:00:00Z", updated_at="2026-09-30T20:00:00Z",
              source_branch="platform-agent/someone-else")
    old = fixture("commit-by-sha.json")
    old["committed_date"] = "2026-09-30T20:00:00.000+00:00"
    gitlab.routes[f"{PROJECT}/repository/commits/{fixture('mr-view.json')['sha']}"] = (200, old)
    stash(f"Opened {MR3_URL}")
    result = pr_check(accepts_stream_pull_request=True).verify(30)
    assert result.success is False
    assert "audit stream's `finish` names" in result.reason
    stream_env(monkeypatch, repo="example-group/other")
    route_mr3(gitlab, created_at="2026-09-30T20:00:00Z", updated_at="2026-09-30T20:00:00Z",
              source_branch=f"platform-agent/fix-{AUDIT}-1")
    gitlab.routes[f"{PROJECT}/repository/commits/{fixture('mr-view.json')['sha']}"] = (200, old)
    result = pr_check(accepts_stream_pull_request=True).verify(30)
    assert result.success is False
    assert "other than this job's" in result.reason


def test_a_merged_earlier_merge_request_spends_the_branch_and_a_forks_does_not(env, gitlab):
    # GitLab's `closed` leaves merged out; `source_branch` alone matches forks.
    stash(route_spent(gitlab, carried=False, named=True))
    listing_key = f"{PROJECT}/merge_requests?state=all&source_branch=platform-agent%2Fproto-1&per_page=100"
    status, listed = gitlab.routes[listing_key]
    merged = {**listed[0], "state": "merged"}
    gitlab.routes[listing_key] = (200, [merged])
    assert pr_check(reuses_spent_branch=True).verify(30).success is True
    fork = {**listed[0], "source_project_id": 99}
    gitlab.routes[listing_key] = (200, [fork])
    result = pr_check(reuses_spent_branch=True).verify(30)
    assert result.success is False
    assert "carries no merge request that this run opened and closed" in result.reason


@pytest.mark.parametrize("host", ["https://gitlab.example.com", "gitlab.example.com/", "gitlab.example.com:8443", "a b"])
def test_a_gitlab_host_that_is_not_a_bare_hostname_is_an_error(env, gitlab, monkeypatch, host):
    monkeypatch.setenv(forges.GITLAB_HOST_ENV_VAR, host)
    stash(f"Opened {MR3_URL}")
    result = pr_check().verify(30)
    assert result.status == "error"
    assert "not a bare hostname" in result.reason
    assert gitlab.calls == []


def test_github_url_shapes_are_mains():
    # An owner or name starting with `_` or `.` was never a GitHub URL here.
    assert forges.issue_refs("https://github.com/_a/b/issues/1", "github") == []
    assert forges.proposal_refs("https://github.com/a/.b/pull/2", "github") == []
    assert forges.issue_refs("https://gitlab.com/_a/b/-/issues/1", "gitlab") == [("_a/b", 1)]
