/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/yaml"

	agentv1alpha1 "github.com/gke-labs/kube-agents/k8s-operator/api/v1alpha1"
)

// a2aGatewayIngressFixturePath is the A2A gateway's rendered ingress surface
// with both doors armed: its three NetworkPolicies (the two doors' and the
// gateway's own), the gateway pod's labels and the gateway container's declared
// ports, nothing else. The conformance suite reads it
// (tests/conformance, C1) to hold the policies to "the collector, on the
// metrics port, and nobody else": the suite cannot run Go, and no golden
// renders mode next, so this file is the contract between the two.
//
// Compared as parsed YAML, as the goldens are, because the file is kept in
// prettier's style for CI's prettier check and the marshaller's is not.
//
// Regenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update
// then: prettier --write internal/controller/testdata/a2a-gateway-ingress.yaml
const a2aGatewayIngressFixturePath = "testdata/a2a-gateway-ingress.yaml"

// a2aGatewayIngressFixtureHeader opens the fixture, so a reader who finds it
// knows it is generated and from where.
const a2aGatewayIngressFixtureHeader = "# Generated by TestRenderedA2AGatewayIngressMatchesTheConformanceFixture\n" +
	"# (k8s-operator/internal/controller/platformagent_a2a_gateway_metrics_test.go)\n" +
	"# with A2A_INJECT_BACKEND and A2A_AGENT_DOOR on. Read by tests/conformance.\n" +
	"# Regenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update\n" +
	"# then prettier --write this file.\n"

// a2aGatewayMetricsEnvtestNamespace is the namespace the envtest case renders into.
const a2aGatewayMetricsEnvtestNamespace = "a2a-gateway-metrics"

// a2aGatewayDoorPorts is the gateway container's ports without the metrics
// listener's: what the door tests count.
func a2aGatewayDoorPorts(ports []corev1.ContainerPort) []corev1.ContainerPort {
	var doors []corev1.ContainerPort
	for _, p := range ports {
		if p.Name != a2aGatewayMetricsPortName {
			doors = append(doors, p)
		}
	}
	return doors
}

// assertA2AGatewayFenceAdmitsOnlyTheCollector holds one gateway fence to
// exactly one ingress rule: from the gke-gmp-system namespace by its
// metadata.name label, no pod selector and no ipBlock beside it, to TCP
// a2aGatewayMetricsPort and no other port.
func assertA2AGatewayFenceAdmitsOnlyTheCollector(t *testing.T, np *networkingv1.NetworkPolicy) {
	t.Helper()
	if len(np.Spec.Ingress) != 1 {
		t.Fatalf("%s carries %d ingress rules, want exactly the collector's: %+v", np.Name, len(np.Spec.Ingress), np.Spec.Ingress)
	}
	rule := np.Spec.Ingress[0]
	if len(rule.From) != 1 {
		t.Fatalf("%s's rule admits %d peers, want the collector's namespace alone: %+v", np.Name, len(rule.From), rule.From)
	}
	peer := rule.From[0]
	if peer.PodSelector != nil || peer.IPBlock != nil || peer.NamespaceSelector == nil {
		t.Errorf("%s's peer is %+v, want a namespace selector and nothing else", np.Name, peer)
	} else if len(peer.NamespaceSelector.MatchExpressions) != 0 ||
		!reflect.DeepEqual(peer.NamespaceSelector.MatchLabels, map[string]string{labelMetadataName: gmpNamespace}) {
		t.Errorf("%s admits namespaces %+v, want %s=%s alone", np.Name, peer.NamespaceSelector, labelMetadataName, gmpNamespace)
	}
	if len(rule.Ports) != 1 || rule.Ports[0].Protocol == nil || *rule.Ports[0].Protocol != corev1.ProtocolTCP ||
		rule.Ports[0].Port == nil || rule.Ports[0].Port.IntValue() != int(a2aGatewayMetricsPort) || rule.Ports[0].EndPort != nil {
		t.Errorf("%s's rule opens %+v, want TCP %d alone", np.Name, rule.Ports, a2aGatewayMetricsPort)
	}
}

// TestTheA2AGatewayDeclaresItsMetricsListener: whatever backend the gateway
// starts on, its container declares the metrics port once under its name and
// carries A2A_METRICS_PORT at the same number, so the listener, the scrape and
// the ingress rule cannot name different ports.
func TestTheA2AGatewayDeclaresItsMetricsListener(t *testing.T) {
	chat := gchatTestAgent("next", true)
	if !a2aChatArmed(chat) {
		t.Fatal("the gchat case does not arm Chat on the gateway; it would test the Discord render twice")
	}
	cases := []struct {
		name  string
		agent *agentv1alpha1.PlatformAgent
		doors bool
	}{
		{"discord", a2aTestAgent(), false},
		{"gchat", chat, false},
		{"both doors", a2aTestAgent(), true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.doors {
				t.Setenv(a2aInjectBackendEnvVar, "true")
				t.Setenv(a2aAgentDoorEnvVar, "true")
			}
			c := buildA2AGatewayDeployment(tc.agent).Spec.Template.Spec.Containers[0]
			var ports []corev1.ContainerPort
			for _, p := range c.Ports {
				if p.Name == a2aGatewayMetricsPortName || p.ContainerPort == a2aGatewayMetricsPort {
					ports = append(ports, p)
				}
			}
			if len(ports) != 1 || ports[0].Name != a2aGatewayMetricsPortName || ports[0].ContainerPort != 9096 {
				t.Fatalf("want exactly one %s container port on 9096, got %+v", a2aGatewayMetricsPortName, c.Ports)
			}
			var found []corev1.EnvVar
			for _, e := range c.Env {
				if e.Name == "A2A_METRICS_PORT" {
					found = append(found, e)
				}
			}
			if len(found) != 1 || found[0].Value != "9096" {
				t.Fatalf("want exactly one A2A_METRICS_PORT=9096, got %+v", found)
			}
			for _, p := range a2aGatewayDoorPorts(c.Ports) {
				if p.ContainerPort == a2aGatewayMetricsPort {
					t.Errorf("door port %+v shares the metrics port", p)
				}
			}
		})
	}
}

// TestTheA2AGatewayFenceMirrorsTheBrokersCollectorRule: the gateway's one
// ingress rule is the credential broker's second rule with the gateway's
// metrics port in it, the same peer byte for byte, on every fence (the
// inject door's, the A2A door's copy, and the gateway's own).
func TestTheA2AGatewayFenceMirrorsTheBrokersCollectorRule(t *testing.T) {
	agent := a2aTestAgent()
	broker := buildCredentialProxyNetworkPolicy(brokerPodAgent())
	if len(broker.Spec.Ingress) != 2 {
		t.Fatalf("the broker's policy has %d rules; this test compares against its second, the collector's", len(broker.Spec.Ingress))
	}
	collector := broker.Spec.Ingress[1]
	for _, np := range []*networkingv1.NetworkPolicy{buildA2AGatewayNetworkPolicy(agent), buildA2ADoorNetworkPolicy(agent), buildA2AGatewayFencePolicy(agent)} {
		t.Run(np.Name, func(t *testing.T) {
			assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
			if !reflect.DeepEqual(np.Spec.Ingress[0].From, collector.From) {
				t.Errorf("the gateway admits %+v, the broker admits %+v; the collector rule is the broker's copied", np.Spec.Ingress[0].From, collector.From)
			}
		})
	}
}

// TestRenderedA2AGatewayIngressMatchesTheConformanceFixture keeps the fixture
// the conformance suite reads equal to what the operator renders.
func TestRenderedA2AGatewayIngressMatchesTheConformanceFixture(t *testing.T) {
	t.Setenv(a2aInjectBackendEnvVar, "true")
	t.Setenv(a2aAgentDoorEnvVar, "true")
	agent := a2aTestAgent()
	dep := buildA2AGatewayDeployment(agent)
	trimmed := &appsv1.Deployment{
		TypeMeta:   dep.TypeMeta,
		ObjectMeta: metav1.ObjectMeta{Name: dep.Name, Namespace: dep.Namespace},
	}
	// The pod template's labels are what each fence's podSelector must
	// match; the Deployment's name is only a proxy for them.
	trimmed.Spec.Template.Labels = dep.Spec.Template.Labels
	for _, c := range dep.Spec.Template.Spec.Containers {
		trimmed.Spec.Template.Spec.Containers = append(trimmed.Spec.Template.Spec.Containers,
			corev1.Container{Name: c.Name, Ports: c.Ports})
	}
	var docs []string
	// The inject door's fence stays first: the conformance mutations anchor on
	// the first match in this file and their descriptions name that fence.
	for _, obj := range []any{buildA2AGatewayNetworkPolicy(agent), buildA2ADoorNetworkPolicy(agent), buildA2AGatewayFencePolicy(agent), trimmed} {
		out, err := yaml.Marshal(obj)
		if err != nil {
			t.Fatal(err)
		}
		docs = append(docs, string(out))
	}
	rendered := a2aGatewayIngressFixtureHeader + "---\n" + strings.Join(docs, "---\n")

	path := filepath.Clean(a2aGatewayIngressFixturePath)
	if *updateAuthMapFixture {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(rendered), 0o644); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the fixture: %v\nRegenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update", err)
	}
	if !reflect.DeepEqual(a2aGatewayFixtureDocs(t, string(want)), a2aGatewayFixtureDocs(t, rendered)) {
		t.Errorf("the rendered gateway ingress and the fixture the conformance suite reads have diverged.\nRegenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update, then prettier --write the file\n--- fixture\n%s\n--- rendered\n%s", want, rendered)
	}
}

// a2aGatewayFixtureDocs parses a multi-document YAML string into its
// documents, dropping the comment-only header. Fails on an empty result, so
// a fixture that lost its body cannot compare equal to a render that did too.
func a2aGatewayFixtureDocs(t *testing.T, data string) []any {
	t.Helper()
	var docs []any
	for _, part := range strings.Split(data, "\n---\n") {
		var doc any
		if err := yaml.Unmarshal([]byte(part), &doc); err != nil {
			t.Fatalf("parsing a fixture document: %v\n%s", err, part)
		}
		if doc != nil {
			docs = append(docs, doc)
		}
	}
	if len(docs) == 0 {
		t.Fatal("the fixture parsed to no documents")
	}
	return docs
}

// TestTheA2AGatewayMetricsSurfaceOnTheAPIServerEnvtest applies the gateway
// Deployment and the fences the way reconcileA2A does, against a real API
// server, and reads back what it accepted: the metrics port and env on the
// container, and on each fence the collector rule alone. The gateway's own
// fence is applied by the second fences pass, the refusal path's, which is
// the one that reads whether the Deployment exists.
func TestTheA2AGatewayMetricsSurfaceOnTheAPIServerEnvtest(t *testing.T) {
	cl, scheme := startEnvtest(t)
	ctx := context.Background()
	t.Setenv(a2aInjectBackendEnvVar, "true")
	t.Setenv(a2aAgentDoorEnvVar, "true")
	if err := cl.Create(ctx, &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: a2aGatewayMetricsEnvtestNamespace}}); err != nil {
		t.Fatalf("creating namespace: %v", err)
	}
	agent := a2aTestAgent()
	agent.Namespace = a2aGatewayMetricsEnvtestNamespace
	agent.UID = types.UID("a2a-gateway-metrics-uid")
	r := &PlatformAgentReconciler{Client: cl, APIReader: cl, Scheme: scheme}

	if _, err := r.reconcileA2ANetworkFences(ctx, agent); err != nil {
		t.Fatalf("reconcileA2ANetworkFences: %v", err)
	}
	if err := r.applyA2AGatewayDeployment(ctx, agent, buildA2AGatewayDeployment(agent)); err != nil {
		t.Fatalf("applyA2AGatewayDeployment: %v", err)
	}
	if _, err := r.reconcileA2ANetworkFences(ctx, agent); err != nil {
		t.Fatalf("reconcileA2ANetworkFences over a running gateway: %v", err)
	}

	dep := &appsv1.Deployment{}
	if err := cl.Get(ctx, client.ObjectKey{Name: a2aGatewayName(agent), Namespace: agent.Namespace}, dep); err != nil {
		t.Fatalf("the API server holds no gateway Deployment: %v", err)
	}
	c := dep.Spec.Template.Spec.Containers[0]
	var metricsPorts []corev1.ContainerPort
	for _, p := range c.Ports {
		if p.Name == a2aGatewayMetricsPortName {
			metricsPorts = append(metricsPorts, p)
		}
	}
	if len(metricsPorts) != 1 || metricsPorts[0].ContainerPort != a2aGatewayMetricsPort || metricsPorts[0].Protocol != corev1.ProtocolTCP {
		t.Errorf("the accepted gateway declares %+v, want one TCP %s on %d", c.Ports, a2aGatewayMetricsPortName, a2aGatewayMetricsPort)
	}
	env := envMapOf(c.Env)
	if got := env[a2aGatewayMetricsPortEnvVar].Value; got != strconv.Itoa(int(a2aGatewayMetricsPort)) {
		t.Errorf("the accepted gateway carries %s=%q, want %d", a2aGatewayMetricsPortEnvVar, got, a2aGatewayMetricsPort)
	}

	for _, name := range []string{a2aInjectName(agent), a2aDoorName(agent), a2aGatewayNetpolName(agent)} {
		np := &networkingv1.NetworkPolicy{}
		if err := cl.Get(ctx, client.ObjectKey{Name: name, Namespace: agent.Namespace}, np); err != nil {
			t.Fatalf("the API server holds no fence %s: %v", name, err)
		}
		assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
	}
}

// a2aGatewayFenceKey is where the gateway's own fence lives: under the
// gateway's name, not a door's, so no door flag decides it. Spelled out here
// rather than through the builder's helper so a rename is a decision this
// test sees.
func a2aGatewayFenceKey(agent *agentv1alpha1.PlatformAgent) types.NamespacedName {
	return types.NamespacedName{Name: agent.Name + "-a2a-gateway-netpol", Namespace: agent.Namespace}
}

// assertA2AGatewayFence reads the gateway's fence and holds it to selecting
// the gateway pod, governing ingress alone (no egress rule set on a pod that
// dials the bus out), and admitting the collector to the metrics port and
// nobody else.
func assertA2AGatewayFence(t *testing.T, ctx context.Context, cl client.Client, agent *agentv1alpha1.PlatformAgent) {
	t.Helper()
	np := &networkingv1.NetworkPolicy{}
	if err := cl.Get(ctx, a2aGatewayFenceKey(agent), np); err != nil {
		t.Fatalf("the gateway renders and no fence %s selects it: %v", a2aGatewayFenceKey(agent).Name, err)
	}
	if !reflect.DeepEqual(np.Spec.PodSelector.MatchLabels, map[string]string{"app": a2aGatewayName(agent)}) {
		t.Errorf("%s selects %+v, want the gateway pod", np.Name, np.Spec.PodSelector)
	}
	if !reflect.DeepEqual(np.Spec.PolicyTypes, []networkingv1.PolicyType{networkingv1.PolicyTypeIngress}) {
		t.Errorf("%s governs %v, want Ingress alone: an Egress type would cut the gateway off the bus", np.Name, np.Spec.PolicyTypes)
	}
	assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
}

// TestTheA2AGatewayFenceComesAndGoesWithTheGateway: the gateway's metrics
// listener binds every interface on every next install, so the fence that
// admits only the collector to it renders wherever the gateway Deployment
// does, door or no door (bnaylor's call on #2473, 2026-10-06), and not where
// the gateway is withheld.
func TestTheA2AGatewayFenceComesAndGoesWithTheGateway(t *testing.T) {
	ctx := context.Background()
	gatewayRendered := func(t *testing.T, cl client.Client, agent *agentv1alpha1.PlatformAgent) {
		t.Helper()
		if err := cl.Get(ctx, types.NamespacedName{Name: a2aGatewayName(agent), Namespace: agent.Namespace}, &appsv1.Deployment{}); err != nil {
			t.Fatalf("precondition: the gateway Deployment was not rendered, so this case proves nothing: %v", err)
		}
	}
	doorFences := func(agent *agentv1alpha1.PlatformAgent) []types.NamespacedName {
		return []types.NamespacedName{
			{Name: a2aInjectName(agent), Namespace: agent.Namespace},
			{Name: a2aDoorName(agent), Namespace: agent.Namespace},
		}
	}

	t.Run("discord, no door", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
		for _, key := range doorFences(agent) {
			if err := cl.Get(ctx, key, &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
				t.Errorf("door fence %s rendered with no door armed (err=%v)", key.Name, err)
			}
		}
	})

	t.Run("chat, no door", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := gchatTestAgent("next", true)
		r, cl, _ := a2aGateTestReconcilerWithoutABackend(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
	})

	t.Run("both doors", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "true")
		t.Setenv(a2aAgentDoorEnvVar, "true")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconcilerWithoutABackend(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
		for _, key := range doorFences(agent) {
			np := &networkingv1.NetworkPolicy{}
			if err := cl.Get(ctx, key, np); err != nil {
				t.Fatalf("door fence %s not rendered with its door armed: %v", key.Name, err)
			}
			assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
		}
	})

	t.Run("withheld for want of a backend", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconcilerWithoutABackend(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		state, err := r.reconcileA2A(ctx, agent)
		if err != nil || !state.gatewayDark {
			t.Fatalf("precondition: want a dark gateway (state=%+v err=%v)", state, err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway is withheld and its fence %s rendered anyway (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}
	})

	t.Run("held for the callout", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		state, err := r.reconcileA2A(ctx, agent)
		if err != nil || !state.gatewayHeld {
			t.Fatalf("precondition: want a held gateway (state=%+v err=%v)", state, err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway is held and its fence %s rendered anyway (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}
	})

	// The Deployment taken away by hand and the flag that was its backend
	// turned off: the next pass is dark, and the fence goes with the gateway.
	t.Run("a dark pass removes it", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "true")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconcilerWithoutABackend(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
		if err := cl.Delete(ctx, &appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Name: a2aGatewayName(agent), Namespace: agent.Namespace}}); err != nil {
			t.Fatal(err)
		}
		t.Setenv(a2aAgentDoorEnvVar, "")
		state, err := r.reconcileA2A(ctx, agent)
		if err != nil || !state.gatewayDark {
			t.Fatalf("precondition: want a dark pass (state=%+v err=%v)", state, err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway is gone and its fence %s survived the dark pass (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}
	})

	// The gateway and its callout both taken away by hand: the callout is
	// re-applied with no serving replica, so the next pass holds the gateway,
	// and the fence goes with it.
	t.Run("a held pass removes it", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
		for _, name := range []string{a2aGatewayName(agent), a2aCalloutName(agent)} {
			if err := cl.Delete(ctx, &appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: agent.Namespace}}); err != nil {
				t.Fatal(err)
			}
		}
		state, err := r.reconcileA2A(ctx, agent)
		if err != nil || !state.gatewayHeld {
			t.Fatalf("precondition: want a held pass (state=%+v err=%v)", state, err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway is held and its fence %s survived the pass (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}
	})

	// The refusal path: reconcileAgentNetworkGuardrails reaches the fences
	// and not the render, so a gateway that exists keeps its fence through a
	// refused CR, and deleting it then does not stick.
	t.Run("the guardrail path keeps it over a running gateway", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		if err := cl.Delete(ctx, &networkingv1.NetworkPolicy{ObjectMeta: metav1.ObjectMeta{Name: a2aGatewayFenceKey(agent).Name, Namespace: agent.Namespace}}); err != nil {
			t.Fatalf("precondition: the fence was not there to delete: %v", err)
		}
		if _, err := r.reconcileA2ANetworkFences(ctx, agent); err != nil {
			t.Fatal(err)
		}
		assertA2AGatewayFence(t, ctx, cl, agent)
	})

	t.Run("the guardrail path renders none without a gateway", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		if _, err := r.reconcileA2ANetworkFences(ctx, agent); err != nil {
			t.Fatal(err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("no gateway exists and the fences rendered %s anyway (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}
	})

	// A flip to today takes the fence with the stack, and the early exit
	// keys on it: a fence left standing alone (the Deployment and the bus
	// fences deleted by hand) still drives the walk.
	t.Run("the flip to today removes it, even alone", func(t *testing.T) {
		t.Setenv(a2aInjectBackendEnvVar, "")
		t.Setenv(a2aAgentDoorEnvVar, "")
		agent := a2aTestAgent()
		r, cl, _ := a2aGateTestReconciler(t, agent)
		theCalloutIsServing(t, ctx, cl, r, agent)
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatal(err)
		}
		gatewayRendered(t, cl, agent)
		assertA2AGatewayFence(t, ctx, cl, agent)
		if err := r.cleanupA2A(ctx, agent); err != nil {
			t.Fatalf("cleanupA2A: %v", err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway's fence %s survived the teardown (err=%v)", a2aGatewayFenceKey(agent).Name, err)
		}

		alone := &networkingv1.NetworkPolicy{
			TypeMeta: metav1.TypeMeta{APIVersion: "networking.k8s.io/v1", Kind: "NetworkPolicy"},
			ObjectMeta: metav1.ObjectMeta{
				Name: a2aGatewayFenceKey(agent).Name, Namespace: agent.Namespace,
				Labels: a2aLabels(agent, "gateway-netpol"),
			},
			Spec: networkingv1.NetworkPolicySpec{PolicyTypes: []networkingv1.PolicyType{networkingv1.PolicyTypeIngress}},
		}
		stored := &agentv1alpha1.PlatformAgent{}
		if err := cl.Get(ctx, client.ObjectKeyFromObject(agent), stored); err != nil {
			t.Fatal(err)
		}
		if err := ctrl.SetControllerReference(stored, alone, r.Scheme); err != nil {
			t.Fatal(err)
		}
		if err := cl.Create(ctx, alone); err != nil {
			t.Fatalf("seeding the fence alone: %v", err)
		}
		if err := r.cleanupA2A(ctx, stored); err != nil {
			t.Fatalf("cleanupA2A over the fence alone: %v", err)
		}
		if err := cl.Get(ctx, a2aGatewayFenceKey(agent), &networkingv1.NetworkPolicy{}); !errors.IsNotFound(err) {
			t.Errorf("the gateway's fence, standing alone, survived the flip (err=%v): the early exit does not key on it", err)
		}
	})
}

// TestTheA2AGatewayFenceIsAppliedOncePerPass counts the server-side applies of
// the gateway's own fence and of the gateway Deployment, in order, across one
// reconcileA2A: the pass that first renders the gateway, then a pass over the
// running install. Each pass applies the fence exactly once, and ahead of the
// Deployment, so the first render never runs the pod unfenced and a running
// install does not pay two identical SSA requests for it (#2473 round 3: the
// fences pass and the render section both wrote it on every pass).
func TestTheA2AGatewayFenceIsAppliedOncePerPass(t *testing.T) {
	t.Setenv(a2aInjectBackendEnvVar, "")
	t.Setenv(a2aAgentDoorEnvVar, "")
	ctx := context.Background()
	agent := a2aTestAgent()

	var applies []string
	funcs := assigningUIDsOnCreate(fakeServerSideApplyInterceptors())
	inner := funcs.Patch
	funcs.Patch = func(ctx context.Context, cl client.WithWatch, obj client.Object, patch client.Patch, opts ...client.PatchOption) error {
		if patch.Type() == types.ApplyPatchType && obj.GetNamespace() == agent.Namespace {
			switch o := obj.(type) {
			case *networkingv1.NetworkPolicy:
				if o.Name == a2aGatewayFenceKey(agent).Name {
					applies = append(applies, "fence")
				}
			case *appsv1.Deployment:
				if o.Name == a2aGatewayName(agent) {
					applies = append(applies, "deployment")
				}
			}
		}
		return inner(ctx, cl, obj, patch, opts...)
	}
	scheme := setupScheme()
	cl := fake.NewClientBuilder().
		WithScheme(scheme).
		WithObjects(agent, sandboxKeysSecret(agent), discordBotSecret(agent)).
		WithStatusSubresource(&agentv1alpha1.PlatformAgent{}).
		WithInterceptorFuncs(funcs).
		Build()
	r := &PlatformAgentReconciler{Client: cl, Scheme: scheme}

	// The helper's own pass holds the gateway (no callout serves yet), so it
	// renders neither; the precondition says so rather than assuming it.
	theCalloutIsServing(t, ctx, cl, r, agent)
	if len(applies) != 0 {
		t.Fatalf("precondition: the held pass applied %v, want nothing of the gateway's", applies)
	}

	want := []string{"fence", "deployment"}
	for _, pass := range []string{"first render", "running install"} {
		applies = nil
		if _, err := r.reconcileA2A(ctx, agent); err != nil {
			t.Fatalf("%s: reconcileA2A: %v", pass, err)
		}
		if !reflect.DeepEqual(applies, want) {
			t.Errorf("%s: gateway applies in order %v, want %v (the fence once, ahead of the Deployment)", pass, applies, want)
		}
	}
	assertA2AGatewayFence(t, ctx, cl, agent)
}
