#!/usr/bin/env python3
"""Tests for check_docs_links.py.

Two kinds of test here, and the split is deliberate.

The synthetic ones build a miniature git repository in a temporary directory
and point the checker at it. They prove each rule *fires*: a lint nobody has
watched fail is a lint nobody knows is wired up. That covers the broken-link
and broken-citation rules and the reachability rule: each shape a reader
starts from, the sidebar read from a planted site config, reach through
links and its dead ends, and every way an allowlist entry goes stale.

The rest run against the real repository. They do not re-run the lint over the
tree -- `make docs-check-links` already does that in CI, and a second copy of
its verdict would only make one dangling citation red two jobs. They pin what
would silently turn the scan into a no-op: a glob that stops matching the
files it exists for, an exempt family whose directory moved out from under its
glob, and this module growing a literal it would then report. A lint that
stops reporting anything looks exactly like a clean repository.

Every design-document path a fixture cites is assembled from DESIGNS and
ARCHITECTURE at runtime. This file is itself a tracked ``.py``, so a literal
``docs/designs/<name>.md`` written here would be scanned and reported as a
broken citation of a document that exists only in a temporary directory.
"""

from __future__ import annotations

import contextlib
import io
import os
import shutil
import subprocess
import unittest
from collections import Counter
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock

import check_docs_links as cdl

REPO = Path(__file__).resolve().parents[1]

# Directory prefixes the scan is anchored on, kept apart from the file names so
# no line of this module is itself a citation (see the module docstring).
DESIGNS = "docs/designs/"
ARCHITECTURE = "docs/architecture/"

PRESENT = DESIGNS + "present.md"
MISSING = DESIGNS + "missing.md"
ON_DISK_ONLY = DESIGNS + "on_disk_only.md"
MISSING_PLAIN = "docs/missing.md"  # outside the scanned directories: a Markdown-link fixture only

# Fixtures for the reachability rule. None is linked by README_LINES unless a
# test says so.
UNLINKED = "docs/unlinked.md"
BLOB_ONLY = "docs/blob-only.md"  # reached by a repository blob URL and nothing else
QUERY_ONLY = "docs/query-only.md"  # reached by a blob URL carrying ?plain=1
ROOT_FILE = "NOTES.md"
NESTED_README = "sub/README.md"
FAMILY_MEMBER = "agents/platform/governance/fixture_sop.md"
FAMILY_NON_MEMBER = "agents/platform/governance/nested/fixture_sop.md"  # `*` stays in its segment
DEEP_FAMILY_MEMBER = "examples/gitops-repo/clusters/a/b/notes.md"  # `**` crosses segments
ROOT_DOT_DIR_FILE = ".tooling/notes.md"
# Dot-directories nested inside a family's area: one where the glob's `*`
# would sit, one where its `**` would. Neither wildcard matches a dot segment,
# so both files are content the family does not cover.
NESTED_DOT_DIR_FILE = "examples/gitops-repo/.github/notes.md"
DEEP_NESTED_DOT_DIR_FILE = "examples/gitops-repo/clusters/.hidden/notes.md"
# Reach through links: a chain from a root, a link from an allowlisted dead
# end (one a link reaches, and one that is itself a root, cited by tool.py),
# and a cycle no root reaches.
CHAINED = DESIGNS + "chained.md"  # linked from PRESENT, which README.md links
DEAD_END = "docs/dead-end.md"  # allowlisted; links DEAD_END_ONLY
DEAD_END_ONLY = "docs/dead-end-only.md"
CITED_DEAD_END_ONLY = DESIGNS + "cited-dead-end-only.md"  # linked from MISSING alone, when that is tracked and allowlisted
CYCLE_A = "docs/cycle-a.md"
CYCLE_B = "docs/cycle-b.md"
# The site, against a planted config: one autogenerated directory, one
# hand-listed group, and a page linked from another page by route.
SITE_CONFIG_LINES = (
    "sidebar: [",
    "  { label: 'Install', items: [",
    "    { label: 'Home', link: '/' },",
    "    { label: 'Listed', link: '/install/listed/' },",
    "  ] },",
    "  { label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },",
    "]",
)
# The same config with an entry and a group commented out, JavaScript-style,
# and a URL whose `//` sits inside a string on a live line, ahead of the
# `link:` it shares the line with: a stripper that read the `//` as a comment
# would cut the link off with it, and the index page would be reported.
# Comments are not navigation; the string is not a comment.
SITE_CONFIG_COMMENTED_LINES = (
    "sidebar: [",
    "  { label: 'Install', items: [",
    "    { label: 'Home', badge: 'https://example.invalid//x', link: '/' },",
    "    // { label: 'Listed', link: '/install/listed/' },",
    "  ] },",
    "  /* { label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] }, */",
    "]",
)
# Starlight's other ways of naming a page: `slug:`, the bare-string shorthand
# for one, a template-literal `link:`, an external `link:` (not a page), and
# an autogenerated directory whose object opens with `collapsed`. The bare
# string after the array is a theme list's, not an entry: it names a page so
# that reading it as one would exempt SITE_UNLISTED and show in the report.
SITE_CONFIG_OTHER_FORMS_LINES = (
    "sidebar: [",
    "  { label: 'Install', items: [",
    "    { label: 'Home', link: '/' },",
    "    { label: 'Slugged', slug: 'install/slugged' },",
    "    'install/shorthand',",
    '    { label: "Templated", link: `/install/templated/` },',
    "    { label: 'Outside', link: 'https://example.invalid/' },",
    "  ] },",
    "  { label: 'Reference', items: [{ autogenerate: { collapsed: true, directory: 'reference' } }] },",
    "],",
    "themes: ['install/unlisted'],",
)
SITE = cdl.SITE_CONTENT_DIR
SITE_INDEX = SITE + "index.mdx"
SITE_404 = SITE + "404.md"
SITE_LISTED = SITE + "install/listed.md"
SITE_UNLISTED = SITE + "install/unlisted.md"
SITE_SLUGGED = SITE + "install/slugged.md"
SITE_SHORTHAND = SITE + "install/shorthand.md"
SITE_TEMPLATED = SITE + "install/templated.md"
SITE_AUTOGENERATED = SITE + "concepts/page.md"
SITE_ROUTED = SITE + "reference/routed.md"  # linked from SITE_LISTED by /kube-agents/ route
SITE_LISTED_LINES = ("# listed", f"[routed]({cdl.SITE_ROUTE_PREFIX}reference/routed/#anchor)")
# The link forms other than `[text](target)`: the `<LinkCard href=...>` a
# site hub page links its sections with, a reference-style definition and an
# autolink. Each fixture is reached by one of them and nothing else. The
# carrier of the last two is a root file, reached by shape; its footnote and
# its quoted `href` are specimens, not links, so neither reaches a document
# nor reads as a broken one, and a definition behind a tab is indented code,
# so the document it names is reached by nothing.
SITE_CARDED = SITE + "install/carded.md"
REF_DEFINED_ONLY = "docs/ref-defined.md"
REF_SINGLE_QUOTED_TITLE = "docs/ref-single-quoted.md"  # a definition with a 'title'
REF_PARENTHESISED_TITLE = "docs/ref-parenthesised.md"  # a definition with a (title)
LINK_PARENTHESISED_TITLE = "docs/link-parenthesised.md"  # an inline link with a (title)
AUTOLINKED_ONLY = "docs/autolinked.md"
REF_TAB_INDENTED = "docs/ref-tab-indented.md"  # defined behind a tab: indented code, no link
OTHER_FORMS = "other-forms.md"
SITE_INDEX_CARD_LINES = (
    "import { LinkCard } from '@astrojs/starlight/components';",
    "",
    "<LinkCard",
    '  title="Carded"',
    f'  href="{cdl.SITE_ROUTE_PREFIX}install/carded/"',
    "/>",
)
OTHER_FORMS_LINES = (
    "# other forms",
    f"[defined]: {REF_DEFINED_ONLY}",
    f"[single]: {REF_SINGLE_QUOTED_TITLE} 'The spec'",
    f"[paren]: {REF_PARENTHESISED_TITLE} (The spec)",
    f"[titled]({LINK_PARENTHESISED_TITLE} (The spec))",
    f"<{cdl.REPO_BLOB_URL_PREFIXES[0]}{AUTOLINKED_ONLY}>",
    "[^1]: footnote",
    '`<a href="specimen.md">`',
    "",
    f"\t[indented]: {REF_TAB_INDENTED}",
)
# Links written inside a comment. An HTML comment in the middle of a line, one
# that opens its line and closes on it, one spanning lines (holding a Markdown
# link, an `href` and a broken link), and an MDX comment around a `<LinkCard>`
# in a site hub page: each hides its target from every reader, so the target
# is reported, and the broken link inside one is not a broken link. A comment
# that opens its line is an HTML block, which runs to the end of the line its
# closer is on, so a link after the closer on that line is raw HTML too: it
# reaches nothing, and a broken one there is not reported. The live links
# still reach their targets: the one after a mid-line comment's closer (inline
# HTML ends at its closer); the one after a `<!--` quoted in inline code (a
# specimen, not an opener), whether the span closes on its line or wraps onto
# the next; the one after a comment that holds a backtick (the comment opened
# first, so the backtick is the comment's, not a span's); and the one inside
# an MDX comment's delimiters in a `.md` file, where they are text.
COMMENTED_OUT = "docs/commented-out.md"
COMMENTED_OUT_SPAN = "docs/commented-out-span.md"
HIDDEN_ON_CLOSING_LINE = "docs/hidden-on-closing-line.md"
LIVE_BESIDE_COMMENT = "docs/live-beside-comment.md"
LIVE_AFTER_SPECIMEN = "docs/live-after-specimen.md"
LIVE_AFTER_WRAPPED_SPECIMEN = "docs/live-after-wrapped-specimen.md"
LIVE_AFTER_BACKTICK_IN_COMMENT = "docs/live-after-backtick-in-comment.md"
LIVE_IN_MDX_DELIMITERS = "docs/live-in-mdx-delimiters.md"
SITE_COMMENTED_CARD = SITE + "install/commented-card.md"
COMMENTS = "comments.md"  # a root file, reached by shape
COMMENTS_LINES = (
    "# comments",
    f"prose <!-- [hidden]({COMMENTED_OUT}) --> [live]({LIVE_BESIDE_COMMENT})",
    f"<!-- [hidden]({COMMENTED_OUT}) --> [hidden]({HIDDEN_ON_CLOSING_LINE}) [gone](nowhere.md)",
    "<!--",
    f"[hidden]({COMMENTED_OUT_SPAN})",
    f'<a href="{COMMENTED_OUT_SPAN}">',
    "[gone](nowhere.md)",
    "-->",
    "a quoted `<!--` is a specimen, so the next line is live:",
    f"[live]({LIVE_AFTER_SPECIMEN})",
    "a span that wraps `<!-- across",
    f"the line break` is a specimen too, so [live]({LIVE_AFTER_WRAPPED_SPECIMEN}) reaches,",
    f"prose <!-- a `x --> b `y` after a backtick in a comment [live]({LIVE_AFTER_BACKTICK_IN_COMMENT}) reaches,",
    f"{{/* and in a .md file [live]({LIVE_IN_MDX_DELIMITERS}) reaches */}}",
)
# A comment opener in the middle of a prose line that nothing in its
# paragraph closes. A comment that opens at the start of a line may span a
# blank line to its closer; one that opens mid-line is inline, so it closes
# in its own paragraph or it is text, as an unclosed backtick run is, and the
# links after it are live and the broken one among them is reported. The
# closed comments come after the stray opener on purpose: without the
# position rule a later closer anywhere in the document was enough to believe
# the opener, it swallowed every paragraph up to that closer, and a green
# broken-link check said nothing about the links it never read. The `.mdx`
# file checks the MDX opener the same way. Each file ends with an opener alone
# on its line that no later closer answers: the one departure from CommonMark
# the checker makes on purpose, text rather than a block to the end of the
# file, so the links after it are read.
STRAY_OPENER = "stray-opener.md"  # a root file, reached by shape
STRAY_OPENER_MDX = "stray-opener.mdx"
HIDDEN_ACROSS_BLANK = "docs/hidden-across-blank.md"
HIDDEN_IN_PARAGRAPH = "docs/hidden-in-paragraph.md"
LIVE_AFTER_STRAY_OPENER = "docs/live-after-stray-opener.md"
LIVE_AFTER_STRAY_MDX_OPENER = "docs/live-after-stray-mdx-opener.md"
LIVE_AFTER_STRAY_BLOCK_OPENER = "docs/live-after-stray-block-opener.md"
LIVE_AFTER_STRAY_MDX_BLOCK_OPENER = "docs/live-after-stray-mdx-block-opener.md"
STRAY_OPENER_GONE_LINE = "and [gone](nowhere.md) is a broken link, while one that <!-- closes in"
STRAY_OPENER_LINES = (
    "# stray opener",
    "an HTML comment opens with <!-- and this one never closes, so",
    "",
    f"the next paragraph is live: [live]({LIVE_AFTER_STRAY_OPENER}) reaches",
    STRAY_OPENER_GONE_LINE,
    f"its own paragraph [hidden]({HIDDEN_IN_PARAGRAPH}) --> hides its link.",
    "",
    "<!--",
    f"[hidden]({HIDDEN_ACROSS_BLANK})",
    "",
    "-->",
    "",
    "<!--",
    "",
    f"an opener alone on its line that nothing later closes is text too, so [live]({LIVE_AFTER_STRAY_BLOCK_OPENER})",
    "reaches, where CommonMark would read a block to the end of the file.",
)
STRAY_OPENER_MDX_LINES = (
    "# stray opener",
    "an MDX comment opens with {/* and this one never closes, so",
    "",
    f"[live]({LIVE_AFTER_STRAY_MDX_OPENER}) reaches.",
    "",
    "{/* a comment closed on its own line, later in the file */}",
    "",
    "{/*",
    "",
    f"[live]({LIVE_AFTER_STRAY_MDX_BLOCK_OPENER}) reaches after a line-opening opener nothing closes.",
)
# A backtick left unpaired in a list item, a table row or a heading, or in the
# paragraph before a blockquote or a thematic break. A renderer parses each of
# those inline on its own, so the backtick is text and the next block's links
# are live; read as one paragraph, it paired with the next backtick in the
# document and hid every link between them, the broken one included. The
# wrapped item keeps the case the paragraph read exists for: a span that wraps
# onto a plain continuation line is still one span. The rule is underscores:
# dashes under a paragraph would be a setext heading, and stars a list item.
# The last two items nest one four spaces in and one behind a tab: a renderer
# measures the nesting from the parent item, so each is an item of its own
# and its link is live; measured from the line start, each was a continuation.
BLOCK_BOUNDARIES = "block-boundaries.md"  # a root file, reached by shape
LIVE_IN_NEXT_ITEM = "docs/live-in-next-item.md"
LIVE_IN_NEXT_ROW = "docs/live-in-next-row.md"
LIVE_UNDER_HEADING = "docs/live-under-heading.md"
LIVE_AFTER_ITEM_WRAP = "docs/live-after-item-wrap.md"
LIVE_IN_QUOTE = "docs/live-in-quote.md"
LIVE_UNDER_RULE = "docs/live-under-rule.md"
LIVE_IN_DEEP_ITEM = "docs/live-in-deep-item.md"  # nested four spaces under `10.`
LIVE_IN_TAB_ITEM = "docs/live-in-tab-item.md"  # nested behind a tab
BLOCK_BOUNDARIES_GONE_LINE = f"| [live]({LIVE_IN_NEXT_ROW}) and [gone](nowhere.md) | `y` |"
BLOCK_BOUNDARIES_LINES = (
    "# block boundaries",
    "",
    "- a literal ` in item one",
    f"- see [live]({LIVE_IN_NEXT_ITEM}) and `code`",
    "",
    "| a lone ` in a cell | x |",
    BLOCK_BOUNDARIES_GONE_LINE,
    "",
    "## a heading with a ` marker",
    f"prose under it links [live]({LIVE_UNDER_HEADING}) and `code`",
    "",
    "- an item whose span wraps `[specimen](specimen.md)",
    f"  onto its continuation line` and then [live]({LIVE_AFTER_ITEM_WRAP}) reaches",
    "",
    "a paragraph with a lone ` marker",
    f"> a quote after it links [live]({LIVE_IN_QUOTE}) and `code`",
    "",
    "a lone ` before a rule",
    "___",
    f"[live]({LIVE_UNDER_RULE}) and `code` under the rule",
    "",
    "10. an item with a literal ` in it",
    f"    - nested four spaces in, [live]({LIVE_IN_DEEP_ITEM}) and `code`",
    "- an item with a literal ` in it",
    f"\t- nested behind a tab, [live]({LIVE_IN_TAB_ITEM}) and `code`",
)
# A span and an inline comment that wrap from one blockquote line to the next.
# A renderer strips the markers and reads the quote's lines as one paragraph,
# so the specimen inside the span is no link, the link after the span's closer
# is live, the link inside the comment renders nowhere and the link after the
# comment's closer is live. Read a `>` line at a time, each backtick was
# unpaired and the opener was text: the specimen was reported as a broken
# link and the hidden document was reached. The quoted item at the end pins
# the boundary inside the quote: a lone backtick in the quoted paragraph
# before it must not pair with the item's span and hide the item's link.
QUOTE_WRAP = "quote-wrap.md"  # a root file, reached by shape
LIVE_IN_QUOTED_ITEM = "docs/live-in-quoted-item.md"  # after a quoted lone backtick
LIVE_AFTER_QUOTED_SPAN = "docs/live-after-quoted-span.md"
HIDDEN_IN_QUOTED_COMMENT = "docs/hidden-in-quoted-comment.md"
LIVE_AFTER_QUOTED_COMMENT = "docs/live-after-quoted-comment.md"
QUOTE_WRAP_LINES = (
    "# quote wrap",
    "",
    "> a span that wraps `[specimen](specimen.md)",
    f"> onto the next quoted line` and then [live]({LIVE_AFTER_QUOTED_SPAN}) reaches",
    ">",
    f"> prose before a comment <!-- [hidden]({HIDDEN_IN_QUOTED_COMMENT})",
    f"> --> and [live]({LIVE_AFTER_QUOTED_COMMENT}) after its closer",
    ">",
    "> a quoted paragraph with a lone ` marker",
    f"> - a quoted item after it links [live]({LIVE_IN_QUOTED_ITEM}) and `code`",
)
# A comment opener alone on its line under a numbered item's continuation,
# four spaces in. CommonMark measures the block indent from the item, so the
# comment is a block that runs across the blank lines to its closer and the
# link inside it renders nowhere; measured from the physical line start it
# read as inline HTML, which cannot cross a blank line, so the opener was text
# and the link inside was live.
INDENTED_OPENER = "indented-opener.md"  # a root file, reached by shape
HIDDEN_UNDER_ITEM = "docs/hidden-under-item.md"
LIVE_AFTER_INDENTED_COMMENT = "docs/live-after-indented-comment.md"
INDENTED_OPENER_LINES = (
    "# indented opener",
    "",
    "1. an item whose continuation holds a commented-out block:",
    "",
    "    <!--",
    "",
    f"    [hidden]({HIDDEN_UNDER_ITEM})",
    "    [gone](nowhere.md)",
    "",
    "    -->",
    "",
    f"   and [live]({LIVE_AFTER_INDENTED_COMMENT}) after it reaches.",
)
# A comment opener that is the first content of its line behind what
# CommonMark lets stand before a block: a tab of indentation, a list marker, a
# blockquote marker, an item that opens a quote, an item nested in an item.
# Each opens an HTML block, as the space-indented opener above does, so the
# comment runs across blank lines to its closer and the links inside render
# nowhere, and a closer on the opener's own line still takes the rest of that
# line with it. Read as inline HTML, the opener whose closer sat past a blank
# line was text and its links were live.
BLOCK_OPENERS = "block-openers.md"  # a root file, reached by shape
HIDDEN_UNDER_TAB = "docs/hidden-under-tab.md"
HIDDEN_IN_ITEM = "docs/hidden-in-item.md"
HIDDEN_IN_QUOTE = "docs/hidden-in-quote.md"
HIDDEN_ON_ITEM_LINE = "docs/hidden-on-item-line.md"
HIDDEN_IN_QUOTED_ITEM = "docs/hidden-in-quoted-item.md"  # an item that opens a quote
HIDDEN_IN_NESTED_ITEM = "docs/hidden-in-nested-item.md"  # an item nested in an item
LIVE_AFTER_BLOCK_OPENERS = "docs/live-after-block-openers.md"
BLOCK_OPENERS_LINES = (
    "# block openers",
    "",
    "1. an item whose continuation is indented with a tab:",
    "",
    "\t<!--",
    "",
    f"\t[hidden]({HIDDEN_UNDER_TAB})",
    "",
    "\t-->",
    "",
    "- <!--",
    f"  [hidden]({HIDDEN_IN_ITEM})",
    "",
    "  -->",
    "",
    "> <!--",
    f"> [hidden]({HIDDEN_IN_QUOTE}) [gone](nowhere.md)",
    ">",
    "> -->",
    "",
    f"2. <!-- a note --> [hidden]({HIDDEN_ON_ITEM_LINE}) [gone](nowhere.md) is raw HTML to the end of the line",
    "",
    "- > <!--",
    f"  > [hidden]({HIDDEN_IN_QUOTED_ITEM})",
    "  >",
    "  > -->",
    "",
    "1. - <!--",
    f"     [hidden]({HIDDEN_IN_NESTED_ITEM})",
    "",
    "     -->",
    "",
    f"- and [live]({LIVE_AFTER_BLOCK_OPENERS}) in the next item reaches.",
)
# An image wrapped in a link, the badge form. The image is read as one link
# and the outer target as another, so the document only the outer target
# names is reached and a broken outer target is reported.
LINKED_IMAGE = "linked-image.md"  # a root file, reached by shape
LINKED_IMAGE_ONLY = "docs/linked-image-only.md"
BADGE = "docs/badge.svg"
LINKED_IMAGE_GONE_LINE = f"[![badge]({BADGE})](docs/nowhere.md)"
LINKED_IMAGE_LINES = (
    "# linked image",
    f"[![badge]({BADGE} 'The badge')]({LINKED_IMAGE_ONLY})",
    LINKED_IMAGE_GONE_LINE,
)
# The live card sits on the closer's line: an MDX comment is an expression and
# ends at its closer even when it opens the line, so the card after it is read.
# Were a line-opening MDX comment to take the rest of its line the way an HTML
# block comment does, the carded page would be reported unreached.
SITE_INDEX_COMMENTED_CARD_LINES = (
    "import { LinkCard } from '@astrojs/starlight/components';",
    "",
    f'{{/* <LinkCard title="Gone" href="{cdl.SITE_ROUTE_PREFIX}install/commented-card/" /> */}}'
    f' <LinkCard title="Carded" href="{cdl.SITE_ROUTE_PREFIX}install/carded/" />',
)

# Files the scan has to keep reaching: the two #992 was filed against, and one
# of each other kind CODE_GLOBS names, each of which cites a design document.
MUST_REACH = (
    "agents/platform/scripts/cluster_agent_reconcile.py",
    "agents/platform/scripts/cluster_agent_profile.py",
    "deploy/sandbox/Dockerfile",
    "a2a/cmd/gateway/main.go",
    "charts/kube-agents/values.yaml",
    "hack/ci-eval-pr.sh",
)

TOOL_LINES = (
    "# tool.py",
    f"# see {PRESENT} §4).",
    f"# see {MISSING}",
    f'print("`{ON_DISK_ONLY}`")',
    f"# {PRESENT}#section, {PRESENT}:12",
)
README_LINES = (
    "# fixture",
    f"[ok]({PRESENT})",
    f"[bad]({MISSING_PLAIN})",
    f"[blob]({cdl.REPO_BLOB_URL_PREFIXES[0]}{BLOB_ONLY})",
    f"[query]({cdl.REPO_BLOB_URL_PREFIXES[0]}{QUERY_ONLY}?plain=1)",
)


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True)


def _write(root: Path, rel: str, text: str) -> Path:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@unittest.skipUnless(shutil.which("git"), "the checker shells out to git")
class SyntheticRepoTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        # Resolved, because tracked_paths() resolves and /tmp may be a symlink.
        self.root = Path(self._tmp.name).resolve()
        _git(self.root, "init", "-q")
        _write(self.root, PRESENT, "# present\n")
        _write(self.root, ON_DISK_ONLY, "# not added\n")
        self.readme = _write(self.root, "README.md", "\n".join(README_LINES) + "\n")
        self.tool = _write(self.root, "tool.py", "\n".join(TOOL_LINES) + "\n")
        _git(self.root, "add", PRESENT, "README.md", "tool.py")
        for target, value in (("REPO", self.root), ("UNLINKED_ALLOWLIST", frozenset())):
            patcher = mock.patch.object(cdl, target, value)
            patcher.start()
            self.addCleanup(patcher.stop)

    def _track(self, *rels: str, links: dict[str, tuple[str, ...]] | None = None) -> None:
        """Track empty documents; `links` maps a document to sibling documents it links."""
        for rel in rels:
            body = [f"# {rel}"]
            for target in (links or {}).get(rel, ()):
                self.assertEqual(Path(target).parent, Path(rel).parent, "links are written as bare names")
                body.append(f"[{target}]({Path(target).name})")
            _write(self.root, rel, "\n".join(body) + "\n")
        _git(self.root, "add", *rels)

    def _unlinked(self) -> list[str]:
        markdown = cdl.tracked_markdown()
        return cdl.check_unlinked(markdown, cdl.reached_files(markdown, cdl.tracked_code()))

    def test_reports_a_dangling_citation_with_its_line(self) -> None:
        problems = cdl.check_code_file(self.tool, cdl.tracked_paths())
        self.assertEqual(
            problems,
            [
                f"tool.py:3: broken citation -> {MISSING}",
                f"tool.py:4: broken citation -> {ON_DISK_ONLY}",
            ],
        )

    def test_trailing_punctuation_anchor_and_line_ref_are_not_the_path(self) -> None:
        problems = cdl.check_code_file(self.tool, cdl.tracked_paths())
        self.assertFalse([p for p in problems if ":2:" in p or ":5:" in p], problems)

    def test_markdown_links_are_still_checked(self) -> None:
        problems = cdl.check_file(self.readme, cdl.tracked_paths())
        self.assertEqual(problems, [f"README.md:3: broken link -> {MISSING_PLAIN}"])

    def test_a_blob_url_is_not_validated_as_a_link(self) -> None:
        """BLOB_ONLY is not tracked, and the blob link to it is still not a broken link."""
        problems = cdl.check_file(self.readme, cdl.tracked_paths())
        self.assertFalse([p for p in problems if BLOB_ONLY in p], problems)

    def test_reports_a_document_nothing_links(self) -> None:
        self._track(UNLINKED)
        self.assertEqual(self._unlinked(), [f"{UNLINKED}: {cdl.UNLINKED_MESSAGE}"])

    def test_a_blob_url_reaches_its_target_with_or_without_a_query(self) -> None:
        self._track(BLOB_ONLY, QUERY_ONLY)
        self.assertEqual(self._unlinked(), [])

    def test_a_code_citation_reaches_its_target(self) -> None:
        self._track(MISSING)  # cited by tool.py, linked by no document
        self.assertEqual(self._unlinked(), [])

    def test_documents_reached_by_shape_are_exempt(self) -> None:
        self._track(ROOT_FILE, NESTED_README, FAMILY_MEMBER, DEEP_FAMILY_MEMBER, ROOT_DOT_DIR_FILE)
        self.assertEqual(self._unlinked(), [])

    def test_reach_follows_links_from_a_root_and_stops_at_dead_ends(self) -> None:
        """PRESENT, which README.md links, links CHAINED and the allowlisted DEAD_END.

        DEAD_END is reached, so its entry is reported as stale; reach through it
        counts for nothing, so DEAD_END_ONLY, which it alone links, is reported
        as unreached. DEAD_END_ONLY vanishes from the report if the link-follow
        dead-end clause in ``reached_files()`` goes. The seed clause is not
        reached here, since a link and not a root reaches DEAD_END; the next
        test pins it.
        """
        self._track(
            CHAINED, DEAD_END, DEAD_END_ONLY, CYCLE_A, CYCLE_B,
            links={CYCLE_A: (CYCLE_B,), CYCLE_B: (CYCLE_A,), DEAD_END: (DEAD_END_ONLY,)},
        )
        dead_end = os.path.relpath(DEAD_END, Path(PRESENT).parent)
        _write(self.root, PRESENT, f"# present\n[chained]({Path(CHAINED).name})\n[dead end]({dead_end})\n")
        with mock.patch.object(cdl, "UNLINKED_ALLOWLIST", frozenset({DEAD_END})):
            self.assertEqual(
                self._unlinked(),
                [
                    f"{CYCLE_A}: {cdl.UNLINKED_MESSAGE}",
                    f"{CYCLE_B}: {cdl.UNLINKED_MESSAGE}",
                    f"{DEAD_END_ONLY}: {cdl.UNLINKED_MESSAGE}",
                    f"{DEAD_END}: {cdl.ALLOWLIST_LINKED_MESSAGE}",
                ],
            )

    def test_an_allowlisted_root_is_a_dead_end_too(self) -> None:
        """MISSING, tracked here, is a root: tool.py cites it and no document links it.

        Allowlisted, it is a dead end from the seed set: its entry is reported
        as stale, since the citation reaches it, and CITED_DEAD_END_ONLY, which
        it alone links, is reported as unreached. CITED_DEAD_END_ONLY vanishes
        from the report if the seed clause in ``reached_files()`` goes, the
        clause that matters when an allowlist entry is a cited design document
        or a sidebar page.
        """
        self._track(MISSING, CITED_DEAD_END_ONLY, links={MISSING: (CITED_DEAD_END_ONLY,)})
        with mock.patch.object(cdl, "UNLINKED_ALLOWLIST", frozenset({MISSING})):
            self.assertEqual(
                self._unlinked(),
                [f"{CITED_DEAD_END_ONLY}: {cdl.UNLINKED_MESSAGE}", f"{MISSING}: {cdl.ALLOWLIST_LINKED_MESSAGE}"],
            )

    def test_the_sidebar_decides_which_site_pages_are_reached(self) -> None:
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_LINES) + "\n")
        self._track(SITE_INDEX, SITE_404, SITE_LISTED, SITE_UNLISTED, SITE_AUTOGENERATED, SITE_ROUTED)
        _write(self.root, SITE_LISTED, "\n".join(SITE_LISTED_LINES) + "\n")
        self.assertEqual(self._unlinked(), [f"{SITE_UNLISTED}: {cdl.UNLINKED_MESSAGE}"])

    def test_a_commented_out_sidebar_entry_or_group_reaches_nothing(self) -> None:
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_COMMENTED_LINES) + "\n")
        self._track(SITE_INDEX, SITE_LISTED, SITE_AUTOGENERATED)
        self.assertEqual(
            self._unlinked(),
            [
                f"{SITE_AUTOGENERATED}: {cdl.UNLINKED_MESSAGE}",
                f"{SITE_LISTED}: {cdl.UNLINKED_MESSAGE}",
            ],
        )

    def test_every_sidebar_form_that_names_a_page_reaches_it(self) -> None:
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_OTHER_FORMS_LINES) + "\n")
        self._track(SITE_INDEX, SITE_SLUGGED, SITE_SHORTHAND, SITE_TEMPLATED, SITE_ROUTED, SITE_UNLISTED)
        self.assertEqual(self._unlinked(), [f"{SITE_UNLISTED}: {cdl.UNLINKED_MESSAGE}"])

    def test_reach_follows_an_href_a_reference_definition_and_an_autolink(self) -> None:
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_LINES) + "\n")
        self._track(
            SITE_INDEX, SITE_CARDED, REF_DEFINED_ONLY, REF_SINGLE_QUOTED_TITLE, REF_PARENTHESISED_TITLE,
            LINK_PARENTHESISED_TITLE, AUTOLINKED_ONLY, REF_TAB_INDENTED, OTHER_FORMS,
        )
        _write(self.root, SITE_INDEX, "\n".join(SITE_INDEX_CARD_LINES) + "\n")
        _write(self.root, OTHER_FORMS, "\n".join(OTHER_FORMS_LINES) + "\n")
        self.assertEqual(self._unlinked(), [f"{REF_TAB_INDENTED}: {cdl.UNLINKED_MESSAGE}"])
        self.assertEqual(cdl.check_file(self.root / OTHER_FORMS, cdl.tracked_paths()), [])

    def test_a_link_inside_a_comment_reaches_nothing_and_breaks_nothing(self) -> None:
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_LINES) + "\n")
        self._track(
            COMMENTS, COMMENTED_OUT, COMMENTED_OUT_SPAN, HIDDEN_ON_CLOSING_LINE, LIVE_BESIDE_COMMENT,
            LIVE_AFTER_SPECIMEN, LIVE_AFTER_WRAPPED_SPECIMEN, LIVE_AFTER_BACKTICK_IN_COMMENT,
            LIVE_IN_MDX_DELIMITERS, SITE_INDEX, SITE_CARDED, SITE_COMMENTED_CARD,
        )
        _write(self.root, COMMENTS, "\n".join(COMMENTS_LINES) + "\n")
        _write(self.root, SITE_INDEX, "\n".join(SITE_INDEX_COMMENTED_CARD_LINES) + "\n")
        self.assertEqual(
            self._unlinked(),
            [
                f"{COMMENTED_OUT_SPAN}: {cdl.UNLINKED_MESSAGE}",
                f"{COMMENTED_OUT}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_ON_CLOSING_LINE}: {cdl.UNLINKED_MESSAGE}",
                f"{SITE_COMMENTED_CARD}: {cdl.UNLINKED_MESSAGE}",
            ],
        )
        self.assertEqual(cdl.check_file(self.root / COMMENTS, cdl.tracked_paths()), [])

    def test_an_opener_nothing_closes_is_text_and_hides_no_later_link(self) -> None:
        self._track(
            STRAY_OPENER, STRAY_OPENER_MDX, HIDDEN_ACROSS_BLANK, HIDDEN_IN_PARAGRAPH,
            LIVE_AFTER_STRAY_OPENER, LIVE_AFTER_STRAY_MDX_OPENER,
            LIVE_AFTER_STRAY_BLOCK_OPENER, LIVE_AFTER_STRAY_MDX_BLOCK_OPENER,
        )
        _write(self.root, STRAY_OPENER, "\n".join(STRAY_OPENER_LINES) + "\n")
        _write(self.root, STRAY_OPENER_MDX, "\n".join(STRAY_OPENER_MDX_LINES) + "\n")
        self.assertEqual(
            self._unlinked(),
            [f"{HIDDEN_ACROSS_BLANK}: {cdl.UNLINKED_MESSAGE}", f"{HIDDEN_IN_PARAGRAPH}: {cdl.UNLINKED_MESSAGE}"],
        )
        tracked = cdl.tracked_paths()
        gone_line = STRAY_OPENER_LINES.index(STRAY_OPENER_GONE_LINE) + 1
        self.assertEqual(
            cdl.check_file(self.root / STRAY_OPENER, tracked),
            [f"{STRAY_OPENER}:{gone_line}: broken link -> nowhere.md"],
        )
        self.assertEqual(cdl.check_file(self.root / STRAY_OPENER_MDX, tracked), [])

    def test_a_backtick_does_not_pair_across_a_block_boundary(self) -> None:
        self._track(
            BLOCK_BOUNDARIES, LIVE_IN_NEXT_ITEM, LIVE_IN_NEXT_ROW, LIVE_UNDER_HEADING, LIVE_AFTER_ITEM_WRAP,
            LIVE_IN_QUOTE, LIVE_UNDER_RULE, LIVE_IN_DEEP_ITEM, LIVE_IN_TAB_ITEM,
        )
        _write(self.root, BLOCK_BOUNDARIES, "\n".join(BLOCK_BOUNDARIES_LINES) + "\n")
        self.assertEqual(self._unlinked(), [])
        gone_line = BLOCK_BOUNDARIES_LINES.index(BLOCK_BOUNDARIES_GONE_LINE) + 1
        self.assertEqual(
            cdl.check_file(self.root / BLOCK_BOUNDARIES, cdl.tracked_paths()),
            [f"{BLOCK_BOUNDARIES}:{gone_line}: broken link -> nowhere.md"],
        )

    def test_a_span_or_a_comment_wraps_across_the_lines_of_one_blockquote(self) -> None:
        self._track(
            QUOTE_WRAP, LIVE_AFTER_QUOTED_SPAN, HIDDEN_IN_QUOTED_COMMENT, LIVE_AFTER_QUOTED_COMMENT,
            LIVE_IN_QUOTED_ITEM,
        )
        _write(self.root, QUOTE_WRAP, "\n".join(QUOTE_WRAP_LINES) + "\n")
        self.assertEqual(self._unlinked(), [f"{HIDDEN_IN_QUOTED_COMMENT}: {cdl.UNLINKED_MESSAGE}"])
        self.assertEqual(cdl.check_file(self.root / QUOTE_WRAP, cdl.tracked_paths()), [])

    def test_an_indented_opener_alone_on_its_line_is_a_block_comment(self) -> None:
        self._track(INDENTED_OPENER, HIDDEN_UNDER_ITEM, LIVE_AFTER_INDENTED_COMMENT)
        _write(self.root, INDENTED_OPENER, "\n".join(INDENTED_OPENER_LINES) + "\n")
        self.assertEqual(self._unlinked(), [f"{HIDDEN_UNDER_ITEM}: {cdl.UNLINKED_MESSAGE}"])
        self.assertEqual(cdl.check_file(self.root / INDENTED_OPENER, cdl.tracked_paths()), [])

    def test_an_opener_behind_a_tab_a_list_marker_or_a_quote_marker_is_a_block_comment(self) -> None:
        self._track(
            BLOCK_OPENERS, HIDDEN_UNDER_TAB, HIDDEN_IN_ITEM, HIDDEN_IN_QUOTE, HIDDEN_ON_ITEM_LINE,
            HIDDEN_IN_QUOTED_ITEM, HIDDEN_IN_NESTED_ITEM, LIVE_AFTER_BLOCK_OPENERS,
        )
        _write(self.root, BLOCK_OPENERS, "\n".join(BLOCK_OPENERS_LINES) + "\n")
        self.assertEqual(
            self._unlinked(),
            [
                f"{HIDDEN_IN_ITEM}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_IN_NESTED_ITEM}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_IN_QUOTE}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_IN_QUOTED_ITEM}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_ON_ITEM_LINE}: {cdl.UNLINKED_MESSAGE}",
                f"{HIDDEN_UNDER_TAB}: {cdl.UNLINKED_MESSAGE}",
            ],
        )
        self.assertEqual(cdl.check_file(self.root / BLOCK_OPENERS, cdl.tracked_paths()), [])

    def test_a_linked_image_reaches_its_target_and_its_outer_target_is_checked(self) -> None:
        self._track(LINKED_IMAGE, LINKED_IMAGE_ONLY)
        _write(self.root, BADGE, "<svg/>\n")
        _git(self.root, "add", BADGE)
        _write(self.root, LINKED_IMAGE, "\n".join(LINKED_IMAGE_LINES) + "\n")
        self.assertEqual(self._unlinked(), [])
        gone_line = LINKED_IMAGE_LINES.index(LINKED_IMAGE_GONE_LINE) + 1
        self.assertEqual(
            cdl.check_file(self.root / LINKED_IMAGE, cdl.tracked_paths()),
            [f"{LINKED_IMAGE}:{gone_line}: broken link -> docs/nowhere.md"],
        )

    def test_without_a_site_config_only_the_convention_pages_are_exempt(self) -> None:
        self._track(SITE_404, SITE_AUTOGENERATED)
        self.assertEqual(self._unlinked(), [f"{SITE_AUTOGENERATED}: {cdl.UNLINKED_MESSAGE}"])

    def test_a_star_stays_in_its_segment_and_a_nested_dot_directory_is_in_scope(self) -> None:
        self._track(FAMILY_NON_MEMBER, NESTED_DOT_DIR_FILE, DEEP_NESTED_DOT_DIR_FILE)
        self.assertEqual(
            self._unlinked(),
            [
                f"{FAMILY_NON_MEMBER}: {cdl.UNLINKED_MESSAGE}",
                f"{NESTED_DOT_DIR_FILE}: {cdl.UNLINKED_MESSAGE}",
                f"{DEEP_NESTED_DOT_DIR_FILE}: {cdl.UNLINKED_MESSAGE}",
            ],
        )

    def test_an_allowlisted_document_that_is_unlinked_passes(self) -> None:
        self._track(UNLINKED)
        with mock.patch.object(cdl, "UNLINKED_ALLOWLIST", frozenset({UNLINKED})):
            self.assertEqual(self._unlinked(), [])

    def test_an_allowlist_entry_that_is_linked_exempt_or_absent_fails(self) -> None:
        self._track(NESTED_README)
        with mock.patch.object(cdl, "UNLINKED_ALLOWLIST", frozenset({PRESENT, UNLINKED, NESTED_README})):
            self.assertEqual(
                self._unlinked(),
                [
                    f"{UNLINKED}: {cdl.ALLOWLIST_UNTRACKED_MESSAGE}",
                    f"{PRESENT}: {cdl.ALLOWLIST_LINKED_MESSAGE}",
                    f"{NESTED_README}: {cdl.ALLOWLIST_EXEMPT_MESSAGE}",
                ],
            )

    def test_main_reports_every_kind_and_exits_one(self) -> None:
        self._track(UNLINKED)
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            rc = cdl.main()
        self.assertEqual(rc, 1)
        # README.md, the present design doc and the unlinked one are the tracked
        # Markdown; tool.py is the code.
        self.assertIn("3 Markdown files and design-doc citations in 1 code files", out.getvalue())
        self.assertEqual(err.getvalue().count("broken link ->"), 1)
        self.assertEqual(err.getvalue().count("broken citation ->"), 2)
        self.assertEqual(err.getvalue().count(cdl.UNLINKED_MESSAGE), 1)

    def test_main_reads_each_document_code_file_and_the_site_config_once(self) -> None:
        """The broken-link checks and the reachability walk share one parse of every input."""
        _write(self.root, cdl.SITE_CONFIG, "\n".join(SITE_CONFIG_LINES) + "\n")
        self._track(UNLINKED)
        reads: Counter[str] = Counter()

        def counted(name: str, real):  # a wrapper for three signatures
            def wrapper(*args):
                reads[f"{name} {args[0]}" if args else name] += 1
                return real(*args)

            return wrapper

        with (
            mock.patch.object(cdl, "markdown_links", counted("links", cdl.markdown_links)),
            mock.patch.object(cdl, "code_citations", counted("citations", cdl.code_citations)),
            mock.patch.object(cdl, "site_sidebar", counted("sidebar", cdl.site_sidebar)),
            contextlib.redirect_stdout(io.StringIO()),
            contextlib.redirect_stderr(io.StringIO()),
        ):
            cdl.main()
        self.assertEqual({key: n for key, n in reads.items() if n != 1}, {}, reads)
        self.assertEqual(sum(key.startswith("links ") for key in reads), len(cdl.tracked_markdown()))
        self.assertEqual(sum(key.startswith("citations ") for key in reads), len(cdl.tracked_code()))
        self.assertIn("sidebar", reads)

    def test_main_is_clean_once_every_citation_is_tracked(self) -> None:
        _write(self.root, MISSING, "# now present\n")
        _write(self.root, MISSING_PLAIN, "# now present\n")
        _git(self.root, "add", MISSING, ON_DISK_ONLY, MISSING_PLAIN)
        out = io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(io.StringIO()):
            rc = cdl.main()
        self.assertEqual(rc, 0, out.getvalue())
        self.assertIn("a reader reaches every document.", out.getvalue())


class CitationPatternTest(unittest.TestCase):
    def test_mdx_glob_and_placeholder_do_not_match(self) -> None:
        for text in (
            DESIGNS + "page.mdx",
            DESIGNS + "*.md",
            DESIGNS + "{name}.md",
            "docs/site/src/content/docs/deploy/x.md",
        ):
            with self.subTest(text=text):
                self.assertIsNone(cdl.CITATION_RE.search(text))

    def test_dotted_name_and_both_directories_match_whole(self) -> None:
        dotted = DESIGNS + "a.b.md"
        security = ARCHITECTURE + "03-security-model.md"
        memory = DESIGNS + "memory.md"
        for text, expected in (
            (f"see {dotted}.", dotted),
            (f"({security}#x)", security),
            (f"`{memory}`", memory),
        ):
            with self.subTest(text=text):
                m = cdl.CITATION_RE.search(text)
                self.assertIsNotNone(m)
                self.assertEqual(m.group(0), expected)


class FamilyGlobTest(unittest.TestCase):
    def test_single_star_stays_in_a_segment_and_double_star_crosses(self) -> None:
        single = cdl.glob_to_regex("a/*/b.md")
        double = cdl.glob_to_regex("a/*/**")
        self.assertTrue(single.match("a/x/b.md"))
        self.assertFalse(single.match("a/x/y/b.md"))
        self.assertFalse(single.match("a/x/b.mdx"))
        self.assertTrue(double.match("a/x/y/z.md"))
        self.assertFalse(double.match("a/b.md"))

    def test_neither_wildcard_matches_a_segment_that_starts_with_a_dot(self) -> None:
        single = cdl.glob_to_regex("a/*/b.md")
        double = cdl.glob_to_regex("a/*/**")
        self.assertFalse(single.match("a/.x/b.md"))
        self.assertFalse(double.match("a/.x/y.md"))
        self.assertFalse(double.match("a/x/.y/z.md"))
        self.assertFalse(double.match("a/x/.z.md"))
        self.assertTrue(double.match("a/x/y.z.md"))


class RealRepoTest(unittest.TestCase):
    def test_the_scan_reaches_the_files_it_exists_for(self) -> None:
        code = {p.relative_to(REPO).as_posix() for p in cdl.tracked_code()}
        for rel in MUST_REACH:
            with self.subTest(file=rel):
                self.assertIn(rel, code)

    def test_the_site_config_still_yields_a_sidebar(self) -> None:
        """A reworded config would exempt no site page and report all of them; pin the shapes read."""
        directories, pages = cdl.site_sidebar()
        self.assertTrue(directories)
        self.assertTrue(pages)
        self.assertTrue(all(p.is_file() for p in pages), sorted(pages))

    def test_every_exempt_family_still_has_members(self) -> None:
        """A family whose directory moved would exempt nothing and hide nothing; say so."""
        markdown = [p.relative_to(REPO).as_posix() for p in cdl.tracked_markdown()]
        for glob in cdl.LINK_EXEMPT_FAMILY_GLOBS:
            with self.subTest(glob=glob):
                pattern = cdl.glob_to_regex(glob)
                self.assertTrue(any(pattern.match(rel) for rel in markdown))

    def test_this_module_contains_no_literal_citation(self) -> None:
        """The guard behind the module docstring: a literal here would fail docs-check."""
        problems = cdl.check_code_file(Path(__file__).resolve(), cdl.tracked_paths())
        self.assertEqual(problems, [])


if __name__ == "__main__":
    unittest.main()
